//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessUyg.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgzersizProgram3
    {
        public int ID { get; set; }
        public string Gün { get; set; }
        public string Egzersiz { get; set; }
        public string Set { get; set; }
        public string Tekrar { get; set; }
        public string Not { get; set; }
    }
}
