//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessUyg.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyelikFiyat
    {
        public int ID { get; set; }
        public string Üyelik { get; set; }
        public string Fiyat { get; set; }
    }
}
