//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessUyg.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> DoğumTarihi { get; set; }
        public string Mail { get; set; }
        public string TelNo { get; set; }
        public Nullable<System.DateTime> ÜyelikBitiş { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Kilo { get; set; }
        public string ÜyelikTürü { get; set; }
    }
}
